/* eslint-disable @typescript-eslint/no-require-imports */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const path = require('node:path'); const vm = require('node:vm');
const ts = require('typescript'); const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const root = path.resolve(__dirname, '..');
function load(relative) {
  const file = path.join(root, relative);
  const exports = {};
  const compiled = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: {
    module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true,
  } }).outputText;
  vm.runInNewContext(compiled, { exports, process, require: name => {
    if (!name.startsWith('@/') && !name.startsWith('.')) return require(name);
    const base = name.startsWith('@/') ? path.join(root, name.slice(2)) : path.resolve(path.dirname(file), name);
    const target = ['.tsx', '.ts', '.js'].map(ext => base + ext).find(p => fs.existsSync(p));
    return target.endsWith('.js') ? require(target) : load(path.relative(root, target));
  } });
  return exports;
}
const row = { metric_key: 'is.operating_cash_flow', fact_id: 1988, publication_id: 2246,
  value_numeric_exact: '111482000000.000000000000', unit: 'currency', currency: 'USD', fact_nature: 'actual',
  source_role: 'primary_as_filed_actual', period_type: 'FY', fiscal_year: 2025, period_basis: 'duration',
  period_start: '2024-09-29', period_end: '2025-09-27' };
const evidence = { currentness: 'superseded', inputs: [{ ordinal: 1, arithmetic_sign: -1, inputs: [
  { ordinal: 1, arithmetic_sign: 1, statement: { form: '10-K', accession: 'test-accession',
    report_name: 'CONSOLIDATED CASH FLOWS', row_label: 'Cash generated by operating activities',
    column_header: '12 Months Ended Sep. 27, 2025', raw_value: '111482000000', display_value: '111,482',
    display_multiplier: '1000000', unit_measure: 'iso4217:USD', concept: 'private-technical-concept',
    locator: { row_ordinal: 18 } } },
] }] };

test('actual evidence reader leads with readable proof and hides audit fields, preserving nested operands', () => {
  const { FinancialEvidenceReading } = load('components/research/FinancialEvidencePanel.tsx');
  assert.equal(typeof FinancialEvidenceReading, 'function');
  const html = renderToStaticMarkup(React.createElement(FinancialEvidenceReading, { row, evidence, auditExpanded: false }));
  for (const text of ['Operating cash flow', '111,482,000,000', 'USD', '2024-09-29', '2025-09-27',
    'Cash generated by operating activities', '111,482', '1,000,000', 'Subtract', 'superseded']) assert.ok(html.includes(text), text);
  assert.doesNotMatch(html, /private-technical-concept|row_ordinal|111482000000\.000000000000/);
  const audit = renderToStaticMarkup(React.createElement(FinancialEvidenceReading, { row, evidence, auditExpanded: true }));
  assert.match(audit, /private-technical-concept/);
  assert.match(audit, /row_ordinal/);
  assert.match(audit, /111482000000\.000000000000/);
});

test('actual five-step editor is blank and disabled in historical/terminal mode', () => {
  const { ResearchPath } = load('components/research/ResearchPath.tsx');
  const { emptyResearchNotes } = require('./researchPath');
  const html = renderToStaticMarkup(React.createElement(ResearchPath, { notes: emptyResearchNotes(),
    readOnly: true, onChange() { throw Error('must not run'); }, onAppend() {}, onClear() {} }));
  assert.equal((html.match(/<textarea/g) || []).length, 5);
  assert.equal((html.match(/<textarea[^>]*disabled=""/g) || []).length, 5);
  assert.match(html, /Only Save revision/);
  assert.doesNotMatch(html, />Buy|>Own|>Watch/);
});
