/* eslint-disable @typescript-eslint/no-require-imports */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const path = require('node:path'); const vm = require('node:vm');
const ts = require('typescript'); const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const { appendAnalysisObservation } = require('./businessEconomics');
const root = path.resolve(__dirname, '..');
function load(relative) {
  const file = path.join(root, relative);
  const exports = {};
  const compiled = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: {
    module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true,
  } }).outputText;
  vm.runInNewContext(compiled, { exports, process, require: name => {
    if (!name.startsWith('@/') && !name.startsWith('.')) return require(name);
    const base = name.startsWith('@/') ? path.join(root, name.slice(2)) : path.resolve(path.dirname(file), name);
    const target = ['.tsx', '.ts', '.js'].map(ext => base + ext).find(p => fs.existsSync(p));
    return target.endsWith('.js') ? require(target) : load(path.relative(root, target));
  } });
  return exports;
}
const row = { metric_key: 'is.operating_cash_flow', fact_id: 1988, publication_id: 2246,
  value_numeric_exact: '111482000000.000000000000', unit: 'currency', currency: 'USD', fact_nature: 'actual',
  source_role: 'primary_as_filed_actual', period_type: 'FY', fiscal_year: 2025, period_basis: 'duration',
  period_start: '2024-09-29', period_end: '2025-09-27' };
const evidence = { currentness: 'superseded', inputs: [{ ordinal: 1, arithmetic_sign: -1, inputs: [
  { ordinal: 1, arithmetic_sign: 1, statement: { form: '10-K', accession: 'test-accession',
    report_name: 'CONSOLIDATED CASH FLOWS', row_label: 'Cash generated by operating activities',
    column_header: '12 Months Ended Sep. 27, 2025', raw_value: '111482000000', display_value: '111,482',
    display_multiplier: '1000000', unit_measure: 'iso4217:USD', concept: 'private-technical-concept',
    locator: { row_ordinal: 18 } } },
] }] };

test('actual evidence reader leads with readable proof and hides audit fields, preserving nested operands', () => {
  const { FinancialEvidenceReading } = load('components/research/FinancialEvidencePanel.tsx');
  assert.equal(typeof FinancialEvidenceReading, 'function');
  const html = renderToStaticMarkup(React.createElement(FinancialEvidenceReading, { row, evidence, auditExpanded: false }));
  for (const text of ['Operating cash flow', '111,482,000,000', 'USD', '2024-09-29', '2025-09-27',
    'Cash generated by operating activities', '111,482', '1,000,000', 'Subtract', 'superseded']) assert.ok(html.includes(text), text);
  assert.doesNotMatch(html, /private-technical-concept|row_ordinal|111482000000\.000000000000/);
  const audit = renderToStaticMarkup(React.createElement(FinancialEvidenceReading, { row, evidence, auditExpanded: true }));
  assert.match(audit, /private-technical-concept/);
  assert.match(audit, /row_ordinal/);
  assert.match(audit, /111482000000\.000000000000/);
});

test('actual five-step editor is blank and disabled in historical/terminal mode', () => {
  const { ResearchPath } = load('components/research/ResearchPath.tsx');
  const { emptyResearchNotes } = require('./researchPath');
  const html = renderToStaticMarkup(React.createElement(ResearchPath, { notes: emptyResearchNotes(),
    readOnly: true, onChange() { throw Error('must not run'); }, onAppend() {}, onClear() {} }));
  assert.equal((html.match(/<textarea/g) || []).length, 5);
  assert.equal((html.match(/<textarea[^>]*disabled=""/g) || []).length, 5);
  assert.match(html, /Only Save revision/);
  assert.doesNotMatch(html, />Buy|>Own|>Watch/);
});

test('business economics reader exposes formulas, precise operands, evidence and honest ROIC limits', () => {
  const { EconomicsCalculation, BusinessEconomics } = load('components/research/BusinessEconomics.tsx');
  const { businessEconomics } = require('./businessEconomics');
  const input = (key, value, id) => ({ ...row, row_kind: 'fact', row_key: `fact:${id}`, status: 'available',
    fact_id: id, publication_id: id + 1000, metric_key: key, value_numeric_exact: value, fiscal_quarter: null, source_type: 'sec',
    comparison_identity: { identity_complete: true, definition_family: `canonical:${key}`,
      definition_id: key === 'is.revenue' ? 'sec.revenue' : 'sec.operating_income', definition_basis: 'as_filed',
      mapping_version: 'v1', source_mapping_version: 'v1', dimensions_identity: 'empty',
      source_identity: `sec-publication:${id + 1000}`, duration_days: 364, period_duration_kind: 'fiscal_year' } });
  const history = { evaluated_at: '2026-09-10T23:00:00Z', annual_window: { status: 'determined', years: [2023, 2024, 2025] },
    rows: [input('is.revenue', '416161000000', 2198), input('is.operating_income', '133050000000', 2092)] };
  const series = businessEconomics(history).series[0];
  const html = renderToStaticMarkup(React.createElement(EconomicsCalculation, { series, point: series.points.at(-1),
    evaluatedAt: history.evaluated_at, readOnly: false, onSelect() {}, onResearch() {} }));
  for (const expected of ['Operating margin', '31.97%', '133,050,000,000', '416,161,000,000', '2092', '2198', '2024-09-29', '2025-09-27', 'Inspect Operating income', 'Research this calculation']) assert.ok(html.includes(expected), expected);
  const disabled = renderToStaticMarkup(React.createElement(EconomicsCalculation, { series, point: series.points[0],
    evaluatedAt: history.evaluated_at, readOnly: true, onSelect() {}, onResearch() {} }));
  assert.doesNotMatch(disabled, /Research this calculation|133,050,000,000/);
  const page = renderToStaticMarkup(React.createElement(BusinessEconomics, { history, readOnly: true, onSelect() {}, onResearch() {} }));
  for (const text of ['ROIC', 'NOPAT', 'debt', 'split', 'Operating margin', 'Gross margin']) assert.ok(page.includes(text), text);
  const cash = businessEconomics(history).series.find(s => s.id === 'cash_after_ppe');
  const cashHtml = renderToStaticMarkup(React.createElement(EconomicsCalculation, { series: cash, point: cash.points.at(-1),
    evaluatedAt: history.evaluated_at, readOnly: true, onSelect() {}, onResearch() {} }));
  assert.match(cashHtml, /not owner earnings/);
  assert.doesNotMatch(page, /Buy signal|Strong moat|ROIC: [0-9]/);
  const action = page.match(/<button[^>]*disabled=""[^>]*>Research this calculation/);
  assert.ok(action, 'read-only mode disables research insertion');
});

const casePageSource = fs.readFileSync(path.join(root, 'app/(dashboard)/research/cases/[id]/page.tsx'), 'utf8');
const casePageTree = ts.createSourceFile('page.tsx', casePageSource, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
let annualFinancialsTable;
function findAnnualFinancialsTable(node) {
  if (ts.isJsxSelfClosingElement(node) && node.tagName.getText(casePageTree) === 'AnnualFinancialsTable') annualFinancialsTable = node;
  ts.forEachChild(node, findAnnualFinancialsTable);
}
findAnnualFinancialsTable(casePageTree);
assert.ok(annualFinancialsTable, 'The annual financials table must remain reachable from the research case page');
function annualFinancialsProp(name) {
  const attribute = annualFinancialsTable.attributes.properties.find(item => item.name?.getText(casePageTree) === name);
  assert.ok(attribute?.initializer && ts.isJsxExpression(attribute.initializer), `Missing ${name} expression`);
  return attribute.initializer.expression.getText(casePageTree);
}
const economicsReadOnly = annualFinancialsProp('readOnly');
const economicsOnResearch = annualFinancialsProp('onResearch');
function executePage(code, context) {
  const compiled = ts.transpileModule(code, { compilerOptions: {
    target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS,
  } }).outputText;
  return vm.runInNewContext(compiled, context);
}
function callbackFixture({ terminal = false, conflict = false, pending = false, loadedHead = 2, workspaceHead = 2 } = {}) {
  const researchNotes = { observation: 'Existing observation', explanations: 'Existing explanation',
    evidenceNeeded: 'Existing evidence need', falsification: 'Existing falsifier', judgment: 'Existing judgment' };
  const result = { updates: [], requests: [], scrolls: 0 };
  const context = {
    terminal, conflict, loadedHead, workspace: { case: { head_revision_number: workspaceHead } },
    saveMutation: { isPending: pending }, draft: { researchNotes }, appendAnalysisObservation,
    updateDraft: patch => result.updates.push(patch),
    document: { getElementById: () => ({ scrollIntoView: () => { result.scrolls += 1; } }) },
    apiClient: { post: (...args) => { result.requests.push(args); } }, callbackText: 'Display calculation context',
  };
  return { context, result, researchNotes };
}

test('actual economics research callback rejects unsafe draft heads and aligned editing stays local', () => {
  const blocked = [
    { terminal: true },
    { conflict: true },
    { pending: true },
    { loadedHead: null },
    { loadedHead: 2, workspaceHead: 3 },
  ];
  for (const state of blocked) {
    const setup = callbackFixture(state);
    assert.equal(executePage(`(${economicsReadOnly})`, setup.context), true, JSON.stringify(state));
    executePage(`(${economicsOnResearch})(callbackText)`, setup.context);
    assert.equal(setup.result.updates.length, 0, JSON.stringify(state));
    assert.equal(setup.result.scrolls, 0, JSON.stringify(state));
    assert.equal(setup.result.requests.length, 0, JSON.stringify(state));
  }

  const aligned = callbackFixture();
  assert.equal(executePage(`(${economicsReadOnly})`, aligned.context), false);
  executePage(`(${economicsOnResearch})(callbackText)`, aligned.context);
  assert.equal(aligned.result.updates.length, 1);
  assert.deepEqual(aligned.result.updates[0].researchNotes, {
    ...aligned.researchNotes,
    observation: 'Existing observation\n\nDisplay calculation context',
  });
  assert.equal(aligned.result.scrolls, 1);
  assert.equal(aligned.result.requests.length, 0);
});
